import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./utils/providers/QueryProvider";
import { FilterContextProvider } from "./utils/providers/FilterContextProvider";
import Header from "./_components/Header";
import ReduxProvider from "./utils/providers/ReduxProvider";
import { AuthContextProvider } from "./utils/providers/AuthContextProvider";

export const metadata: Metadata = {
  title: "Images Filtering",
  description: "Generated by Engr. Tambi",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthContextProvider>
      <html lang="en">
        <body className="mx-auto w-[80%] ">
          <ReduxProvider>
            <QueryProvider>
              <FilterContextProvider>
                <Header />
                {children}
              </FilterContextProvider>
            </QueryProvider>
          </ReduxProvider>
        </body>
      </html>
    </AuthContextProvider>
  );
}
