import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./utils/providers/QueryProvider";
import { FilterContextProvider } from "./utils/providers/FilterContextProvider";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Images Filtering",
  description: "Generated by Engr. Tambi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mx-auto w-[80%] ">
        <QueryProvider>
          <FilterContextProvider>
            <Header />
            {children}
          </FilterContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
